export const GET_COMMENT ="GET_COMMENT"
export const GET_COMMENT_SUCCESS ="GET_COMMENT_SUCCESS"
export const GET_COMMENT_FAILED ="GET_COMMENT_FAILED"

export const ADD_COMMENT = "ADD_COMMENT"
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS"
export const ADD_COMMENT_FAILED = "ADD_COMMENT_FAILED"

export const DELETE_COMMENT = "DELETE_COMMENT"
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS"
export const DELETE_COMMENT_FAILED = "DELETE_COMMENT_FAILED"